name: k-diffusion
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - backoff=2.2.1
  - blas=1.0
  - blessed=1.20.0
  - boto3=1.29.1
  - botocore=1.32.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2024.2.2
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - croniter=1.3.7
  - cryptography=39.0.1
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.99
  - cuda-runtime=12.1.0
  - cudatoolkit=11.3.1
  - dateutils=0.6.12
  - deepdiff=6.7.1
  - exceptiongroup=1.2.0
  - fastapi=0.103.0
  - ffmpeg=4.3
  - freetype=2.12.1
  - fsspec=2023.10.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - h11=0.14.0
  - idna=3.4
  - inquirer=3.1.4
  - intel-openmp=2023.1.0
  - itsdangerous=2.0.1
  - jinja2=3.1.3
  - jmespath=1.0.1
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.9.0.20
  - libcurand=10.3.5.119
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lightning=2.0.9.post0
  - lightning-cloud=0.5.57
  - lightning-utilities=0.9.0
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - mdurl=0.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.0.3
  - mpfr=4.0.2
  - mpi=1.0
  - mpi4py=3.1.4
  - mpich=3.3.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openssl=3.0.13
  - ordered-set=4.1.0
  - orjson=3.9.10
  - packaging=23.1
  - pillow=9.4.0
  - pip=23.1.2
  - pycparser=2.21
  - pydantic=1.10.12
  - pygments=2.15.1
  - pyjwt=2.4.0
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - python-editor=1.0.4
  - python-multipart=0.0.6
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - pytorch-lightning=2.0.3
  - pytorch-mutex=1.0
  - readchar=4.0.5
  - readline=8.2
  - requests=2.31.0
  - rich=13.3.5
  - s3transfer=0.7.0
  - setuptools=67.8.0
  - six=1.16.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - starlette=0.27.0
  - starsessions=1.3.0
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=2.2.1
  - torchmetrics=1.1.2
  - torchtriton=2.2.0
  - torchvision=0.17.1
  - tqdm=4.65.0
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - urllib3=1.26.16
  - uvicorn=0.20.0
  - websockets=10.4
  - wheel=0.38.4
  - xz=5.4.2
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - accelerate==0.20.3
    - anyio==4.3.0
    - appdirs==1.4.4
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.2.1
    - async-lru==2.0.4
    - attrs==23.1.0
    - babel==2.14.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - blobfile==2.0.2
    - boltons==23.0.0
    - clean-fid==0.1.35
    - click==8.1.3
    - clip-anytorch==2.5.2
    - comm==0.2.2
    - contourpy==1.1.0
    - cycler==0.11.0
    - debugpy==1.8.1
    - decorator==5.1.1
    - deepspeed==0.14.0
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - einops==0.6.1
    - executing==1.2.0
    - fastjsonschema==2.19.1
    - filelock==3.12.2
    - fonttools==4.41.1
    - fqdn==1.5.1
    - gitdb==4.0.10
    - gitpython==3.1.31
    - google-auth==2.28.2
    - google-auth-oauthlib==1.0.0
    - gpytorch==1.11
    - grpcio==1.62.1
    - h5py==3.9.0
    - hdf5storage==0.1.19
    - hjson==3.1.0
    - httpcore==1.0.4
    - httpx==0.27.0
    - imageio==2.31.1
    - importlib-metadata==7.0.2
    - importlib-resources==5.12.0
    - ipdb==0.13.13
    - ipykernel==6.29.3
    - ipython==8.12.2
    - ipywidgets==8.1.2
    - isoduration==20.11.0
    - jaxtyping==0.2.19
    - jedi==0.18.2
    - joblib==1.3.2
    - json5==0.9.22
    - jsonmerge==1.9.0
    - jsonpointer==2.4
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - jupyter==1.0.0
    - jupyter-client==8.6.1
    - jupyter-console==6.6.3
    - jupyter-core==5.7.2
    - jupyter-events==0.9.1
    - jupyter-lsp==2.2.4
    - jupyter-server==2.13.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.1.4
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.25.4
    - jupyterlab-widgets==3.0.10
    - k-diffusion==0.0.15
    - kiwisolver==1.4.4
    - kornia==0.6.12
    - lazy-loader==0.2
    - linear-operator==0.5.2
    - lpips==0.1.4
    - lxml==4.9.3
    - markdown==3.6
    - markupsafe==2.1.5
    - matplotlib==3.7.2
    - matplotlib-inline==0.1.6
    - mistune==3.0.2
    - nbclient==0.10.0
    - nbconvert==7.16.2
    - nbformat==5.10.2
    - nest-asyncio==1.6.0
    - ninja==1.11.1.1
    - notebook==7.1.1
    - notebook-shim==0.2.4
    - opencv-python==4.8.0.74
    - overrides==7.7.0
    - pandocfilters==1.5.1
    - parso==0.8.3
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.2.0
    - prometheus-client==0.20.0
    - prompt-toolkit==3.0.38
    - protobuf==4.23.3
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py-cpuinfo==9.0.0
    - pycryptodomex==3.18.0
    - pynvml==11.5.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-json-logger==2.0.7
    - pytorch-fid==0.3.0
    - pytz==2024.1
    - pyyaml==6.0
    - pyzmq==25.1.2
    - qtconsole==5.5.1
    - qtpy==2.4.1
    - referencing==0.33.0
    - regex==2023.6.3
    - resize-right==0.0.2
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.18.0
    - scikit-learn==1.3.2
    - send2trash==1.8.2
    - sentry-sdk==1.25.1
    - setproctitle==1.3.2
    - smmap==5.0.0
    - sniffio==1.3.1
    - stack-data==0.6.2
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - terminado==0.18.1
    - threadpoolctl==3.3.0
    - tifffile==2023.4.12
    - tinycss2==1.2.1
    - tomli==2.0.1
    - torchdiffeq==0.2.3
    - torchsde==0.2.5
    - tornado==6.4
    - traitlets==5.9.0
    - trampoline==0.1.2
    - typeguard==2.13.3
    - types-python-dateutil==2.8.19.20240311
    - uri-template==1.3.0
    - wandb==0.15.4
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.7.0
    - widgetsnbextension==4.0.10
    - zipp==3.15.0
