name: inpainting
sigma_s: 0.05
mask_opt:
  mask_type: random # box, random
  # mask_len_range: !!python/tuple [64, 65]  # for box
  mask_prob_range: !!python/tuple [0.5, 0.5]  # for random
  image_size: 128

